version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ottobon-dfo-frontend:latest
    container_name: ottobon_frontend
    ports:
      - "8080:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
